### ISSUE TITLE
DFUI数据集

### ISSUE THREAD

**Issue by xiejing115** [xiaoDetection/Learning-Heavily-Degraed-Prior#1]
您的方法非常的巧妙，我看了您的论文，不知道DFUI数据集是如何从水下数据集筛选的，是一张图片的每个类别的AP ，只要满足有一个类别的AP 大于60就可以纳入DFUI数据集吗？可以分享一下DFUI数据集吗，谢谢！

**Comment by xiaoDetection** [comment]
所有类别AP的均值大于60入选DFUI数据集。
DFUI数据集我们已经重新上传了。
感谢您的支持！

**Comment by xiaoDetection** [comment]
所有类别AP的均值大于60入选DFUI数据集。
DFUI数据集我们已经重新上传了。
感谢您的支持！

**Comment by wojiaosun** [comment]
Readme中<config_file> <checkpoint_file> <work_dir>具体指什么呢？

**Comment by wojiaosun** [comment]
TypeError: FormatCode() got an unexpected keyword argument 'verify'  我训练的时候报这个错误是什么原因呢

**Comment by xiaoDetection** [comment]
> Readme中<config_file> <checkpoint_file> <work_dir>具体指什么呢？

config_file是配置文件，checkpoint_file是测试时使用的权重文件，work_dir 是训练中保存log和chechkpoint的路径。
详细信息您可以参考mmdetection文档：https://mmdetection.readthedocs.io/en/v2.22.0/

**Comment by xiaoDetection** [comment]
> TypeError: FormatCode() got an unexpected keyword argument 'verify' 我训练的时候报这个错误是什么原因呢

需要降低yapf版本：`pip install yapf==0.40.1`

**Comment by wojiaosun** [comment]
> > Readme中<config_file> <checkpoint_file> <work_dir>具体指什么呢？
> 
> config_file是配置文件，checkpoint_file是测试时使用的权重文件，work_dir 是训练中保存log和chechkpoint的路径。 详细信息您可以参考mmdetection文档：https://mmdetection.readthedocs.io/en/v2.22.0/

好的谢谢，配置文件和权重文件在mmdetection文档中有么，还是需要自己写，还是说训练之后生成的呢

**Comment by wojiaosun** [comment]
> > > Readme中<config_file> <checkpoint_file> <work_dir>具体指什么呢？
> > 
> > 
> > config_file是配置文件，checkpoint_file是测试时使用的权重文件，work_dir 是训练中保存log和chechkpoint的路径。 详细信息您可以参考mmdetection文档：https://mmdetection.readthedocs.io/en/v2.22.0/
> 
> 好的谢谢，配置文件和权重文件在mmdetection文档中有么，还是需要自己写，还是说训练之后生成的呢

找到了 checkpoint_file，    这个config_file 配置文件是哪个呢

**Comment by xiaoDetection** [comment]
> > > > Readme中<config_file> <checkpoint_file> <work_dir>具体指什么呢？
> > > 
> > > 
> > > config_file是配置文件，checkpoint_file是测试时使用的权重文件，work_dir 是训练中保存log和chechkpoint的路径。 详细信息您可以参考mmdetection文档：https://mmdetection.readthedocs.io/en/v2.22.0/
> > 
> > 
> > 好的谢谢，配置文件和权重文件在mmdetection文档中有么，还是需要自己写，还是说训练之后生成的呢
> 
> 找到了 checkpoint_file， 这个config_file 配置文件是哪个呢

我们使用的config是：configs/rftm/rftm_50.py 和 configs/rftm/rftm_x101.py
