### ISSUE TITLE
datasets download

### ISSUE THREAD

**Issue by zhengCT-CV** [xiaoDetection/Learning-Heavily-Degraed-Prior#3]
Thank you for sharing your valuable work! I am currently facing network issues while trying to download the DFUI and URPC2020 datasets from GitHub. I was wondering if there are any alternative ways to download these datasets or if there's another platform where they are available? Your assistance would be greatly appreciated.

**Comment by xiaoDetection** [comment]
Thank you for your interest! We have uploaded our datasets to Google Drive, and the corresponding links have been updated in the readme. Please try downloading them again.

**Comment by zhengCT-CV** [comment]
非常感谢您提供的下载方式，已经能够成功下载数据，但是我在训练过程中遇到一个问题想向您请教，就是在微调训练过程有多个进程在进行（如图所示），导致我的显存占用很大，有时会出现训练中断，请问这种情况下是正常的吗？为什么会出现这种情况？我是否有其他方法减少进程数从而降低显存占用？非常感谢您的帮助！







未央不见
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaoDetection/Learning-Heavily-Degraded-Prior"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月21日(星期六) 下午3:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaoDetection/Learning-Heavily-Degraded-Prior] datasets download (Issue #3)






Thank you for your interest! We have uploaded our datasets to Google Drive, and the corresponding links have been updated in the readme. Please try downloading them again.

**Comment by xiaoDetection** [comment]
我们在数据预处理阶段计算transmission value **t**使用了GPU加速计算。Pytorch多进程读取数据，所以会出现多进程运行。

您可以参考一下两种方案修改以节约显存：

1. 将transmission value **t**相关的计算放到CPU进行
    修改`mmdet/datasets/coco_custom.py`第20行：
    ```python
    # img = torch.from_numpy(img_np).float().cuda().permute(2, 0, 1).unsqueeze(0) 删除.cuda()
    img = torch.from_numpy(img_np).float().permute(2, 0, 1).unsqueeze(0)
    ```
2. 关闭多进程数据读取
    在`config`文件中设置`workers_per_gpu=0`
    例如修改`configs/rftm/rftm_50.py`第54行：
    ```python
    data = dict(
        # workers_per_gpu=4
        workers_per_gpu=0
    )
    ```
