### ISSUE TITLE
Questions for the construction of the DFUI dataset

### ISSUE THREAD

**Issue by CatchACat083** [xiaoDetection/Learning-Heavily-Degraed-Prior#4]
Thank you for your awesome work! In the article it is mentioned that a DFUI dataset is constructed using a cascade RCNN network to pick up images with AP>60 from URPC2020 and URPC2021 training set. May I ask on which dataset the cascade RCNN network here was trained, before testing the AP values on the two URPC datasets?

**Comment by xiaoDetection** [comment]
Thank you for your interest! It was trained on URPC2020 before testing the AP values.

**Comment by CatchACat083** [comment]
Problem solved! thanks very much for the reply~
